/**
 * ORIGINAL Pixel Dungeon City mob sprites (c) Watabou, watabou/pixel-dungeon,
 * used under the GNU General Public License v3.0.
 *
 * GENERATED FILE — do not edit by hand. Regenerate with:
 *   bun scripts/extract_stage3_city_mobs_sprites.ts
 *
 * Idle frame 0 at (0,0), 16x16 (like mob_bee/mob_monk in
 * original_sprites.ts). Nothing redrawn or recolored.
 */

import type { OriginalSprite } from './original_sprites.js';

// prettier-ignore
export const STAGE3_CITY_MOBS_SPRITES: Record<string, OriginalSprite> = {
  // mob_warlock: warlock.png @(0,0) 16x16 — WarlockSprite.java idle frame 0
  mob_warlock: { w: 16, h: 16, rgba: '////AP///wD///8AAAAAAP///wD///8A////AP///wD///8AAAAAAP///wD///8A////AP///wD///8AAAAAAP///wD///8A////AP///wD///8A////AAAAAAD///8A////AP///wCjo6P/AAAAAP///wD///8A////AP///wCjo6P/AAAAAP///wD///8A////AP///wCjo6P/AAAAAP///wD///8A////AP///wCjo6P/AAAAAP///wD///8A////AP///wCjo6P/AAAAAP///wD///8A////AP///wCjo6P/AAAAAP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AA==' },
  // mob_golem: golem.png @(0,0) 16x16 — GolemSprite.java idle frame 0
  mob_golem: { w: 16, h: 16, rgba: '////AP///wD///8A////AP///wD///8AgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAP///wD///8A////AP///wD///8AgICAAICAgACAgIAAgICAAICAgACAgIAAgICAAP///wD///8A////AP///wD///8A////AP///wD///8A////AAoIB/8zLCv/ZlpX/2ZaV/9mWlf/////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8ACggH/zMsK/9mWlf/ZlpX/2ZaV/////8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wAKCAf/Mywr/zMsK/8zLCv/Mywr/zMsK/9mWlf/////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AA==' },
  // mob_succubus: succubus.png @(0,0) 16x16 — SuccubusSprite.java idle frame 0
  mob_succubus: { w: 16, h: 16, rgba: '////AICAgACAgIAAgICAAFdxrf9Xca3/V3Gt/1dxrf9Xca3/AAAAAICAgAD///8AgICAAICAgACAgIAAgICAAFdxrf9Xca3/V3Gt/1dxrf9Xca3/AAAAAICAgACAgIAA////AICAgACAgIAAgICAAICAgABXca3/V3Gt/1dxrf9Xca3/V3Gt/wAAAACAgIAA////AICAgACAgIAAgICAAFdxrf9Xca3/V3Gt/1dxrf9Xca3/AAAAAICAgAD///8A////AICAgACAgIAAgICAAFdxrf9Xca3/V3Gt/1dxrf9Xca3/AAAAAICAgAD///8A////AICAgACAgIAAgICAAFdxrf9Xca3/V3Gt/1dxrf9Xca3/AAAAAICAgAD///8A////AICAgACAgIAAgICAAFdxrf9Xca3/V3Gt/1dxrf9Xca3/AAAAAICAgAD///8A////AP///wD///8A////AFdxrf9Xca3/V3Gt/1dxrf9Xca3/////AP///wD///8A////AICAgACAgIAAgICAAFdxrf9Xca3/V3Gt/1dxrf9Xca3/AAAAAICAgAD///8AgICAAICAgACAgIAAV3Gt/1dxrf9Xca3/V3Gt/1dxrf8AAAAAgICAAP///wD///8A////AICAgACAgIAAgICAAFdxrf9Xca3/V3Gt/1dxrf9Xca3/AAAAAICAgAD///8A////AP///wCAgIAAgICAAICAgABXca3/V3Gt/1dxrf9Xca3/V3Gt/wAAAACAgIAA////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AA==' },
};
